<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketDataAggregator.Contracts\MarketDataAggregator.Contracts.csproj" />
    <ProjectReference Include="..\MarketDataAggregator.Core\MarketDataAggregator.Core.csproj" />
    <ProjectReference Include="..\MarketDataAggregator.Data\MarketDataAggregator.Data.csproj" />
    <ProjectReference Include="..\MarketDataAggregator.Infrastructure\MarketDataAggregator.Infrastructure.csproj" />
    <ProjectReference Include="..\MarketDataAggregator.Models\MarketDataAggregator.Models.csproj" />
  </ItemGroup>

</Project>
